services:
  - type: web
    name: ingles-idiomatico-new
    env: python
    buildCommand: |
      echo "Starting build process..."
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
      
      echo "Setting up environment..."
      export FLASK_APP=app.py
      export FLASK_ENV=production
      
      echo "Build process completed ✅"
    startCommand: "gunicorn app:app --bind=0.0.0.0:$PORT --workers=4 --threads=4 --timeout=120"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ingles_idiomatico_db
          property: connectionString
      - key: FLASK_APP
        value: app.py
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USE_TLS
        value: "true"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: WEB_CONCURRENCY
        value: "2"
      - key: SQLALCHEMY_TRACK_MODIFICATIONS
        value: "false"
    healthCheckPath: /login
    autoDeploy: true

databases:
  - name: ingles_idiomatico_db
    plan: free
    ipAllowList: [] 