services:
  - type: web
    name: ingles-idiomatico-new
    env: python
    buildCommand: |
      echo "Starting build process..."
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
      
      # Set up deployment directory structure
      echo "Setting up deployment directory..."
      DEPLOY_DIR=/opt/render/project/deploy
      
      # Create static directories
      echo "Creating static directories..."
      mkdir -p $DEPLOY_DIR/static/js
      mkdir -p $DEPLOY_DIR/static/css
      mkdir -p $DEPLOY_DIR/static/audio
      
      # Copy application files
      echo "Copying application files..."
      cp -v app.py config.py extensions.py init_users.py models.py requirements.txt $DEPLOY_DIR/
      
      # Copy static files with verbose output
      echo "Copying static files..."
      echo "Copying JS files..."
      cp -v static/js/* $DEPLOY_DIR/static/js/ || echo "No JS files to copy"
      echo "Copying CSS files..."
      cp -v static/css/* $DEPLOY_DIR/static/css/ || echo "No CSS files to copy"
      echo "Copying audio files..."
      cp -v static/audio/* $DEPLOY_DIR/static/audio/ || echo "No audio files to copy"
      
      # Set permissions
      echo "Setting permissions..."
      chmod -R 755 $DEPLOY_DIR/static
      
      # Verify deployment
      echo "Verifying deployment..."
      echo "Static directory structure:"
      ls -R $DEPLOY_DIR/static
      
      echo "JS files:"
      ls -l $DEPLOY_DIR/static/js/
      echo "CSS files:"
      ls -l $DEPLOY_DIR/static/css/
      
      echo "Setting up environment..."
      export FLASK_APP=app.py
      export FLASK_ENV=production
      export DEPLOY_DIR=$DEPLOY_DIR
      
      echo "Build process completed ✅"
    startCommand: |
      cd /opt/render/project/deploy && \
      PYTHONPATH=/opt/render/project/deploy \
      DEPLOY_DIR=/opt/render/project/deploy \
      gunicorn app:app --bind=0.0.0.0:$PORT --workers=4 --threads=4 --timeout=120 --log-level=debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ingles_idiomatico_db
          property: connectionString
      - key: FLASK_APP
        value: app.py
      - key: DEPLOY_DIR
        value: /opt/render/project/deploy
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USE_TLS
        value: "true"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: WEB_CONCURRENCY
        value: "2"
      - key: SQLALCHEMY_TRACK_MODIFICATIONS
        value: "false"
    healthCheckPath: /login
    autoDeploy: true

databases:
  - name: ingles_idiomatico_db
    plan: free
    ipAllowList: [] 