services:
  - type: web
    name: ingles-idiomatico
    env: python
    region: ohio
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
    autoDeploy: true
    healthCheckPath: /
    numInstances: 1
    plan: free 